id: P006775
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN7856
  title: ཨ་མའི་ཐལ་ལྕག
  author: ''
  volumes:
    fca3a30db1f541359e20159185a84182:
      image_group_id: I3CN7858
      title: ''
      volume_number: 1
      total_pages: 384
