id: P006775
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN7856
  title: ཨ་མའི་ཐལ་ལྕག
  author: ''
  volumes:
    fca3a30db1f541359e20159185a84182:
      image_group_id: I3CN7858
      title: ''
      volume_number: 1
      total_pages: 384
      base_file: v001.txt
